import React from "react";
import PlanetComponent from "../page/PlanetComponent";
import "./Planet.css";
import mercuryImage from "../assets/img/mercuri.jpeg";
import mercurySound from "../assets/sound/mercury.mp3";
import blackwhole from "../assets/sound/bwhole.webp";
import blackwholem from "../assets/sound/bwhole.mp3";

const Planet = () => {
  return (
    <section id="planet">
      <div className="planets-gallery">
        <PlanetComponent
          name="Mercury"
          imageSrc={mercuryImage}
          radiationLevel="Moderate"
          soundSrc={mercurySound}
          description="Size and Position: It's the smallest planet in the solar system, with a diameter of about 4,880 kilometers (3,032 miles). It is the closest planet to the Sun and orbits at an average distance of approximately 57.9 million kilometers (36 million miles). Orbit and Rotation: A year on Mercury (the time it takes to orbit the Sun) is about 88 Earth days, while a day on Mercury (the time it takes to rotate on its axis) is about 59 Earth days. It has a highly eccentric orbit, which means its distance from the Sun varies significantly during its orbit. Surface Features: Mercury's surface is heavily cratered and resembles the Moon's surface, with plains, mountains, valleys, and cliffs. Its surface temperature varies widely, ranging from extremely hot during the day (up to around 430 degrees Celsius or 800 degrees Fahrenheit) due to its proximity to the Sun, to extremely cold at night (around -180 degrees Celsius or -290 degrees Fahrenheit) due to its thin atmosphere that can't retain heat. Atmosphere: Mercury has a very thin atmosphere, composed mainly of trace amounts of helium, hydrogen, oxygen, sodium, calcium, and potassium. Due to its weak gravity and proximity to the Sun, its atmosphere is constantly stripped away by solar winds. Magnetic Field: Mercury has a weak magnetic field, about 1% as strong as Earth's magnetic field. This magnetic field is believed to be generated by a partially molten iron core. Exploration: Several spacecraft have visited Mercury to study its surface and environment. NASA's MESSENGER (MErcury Surface, Space ENvironment, GEochemistry, and Ranging) mission provided detailed information about the planet, mapping its surface and studying its composition, magnetic field, and geology. Water Ice: Despite its proximity to the Sun, some craters near Mercury's poles are in permanent shadow, allowing the possibility of water ice to exist in these areas, protected from the Sun's heat."
        />
        <PlanetComponent
          name="Black Whole"
          imageSrc={blackwhole}
          radiationLevel="Moderate"
          soundSrc={blackwholem}
          description="Singularity: At the center of a black hole lies a gravitational singularity, where the mass is thought to be infinitely dense and the gravitational forces are incredibly strong.

          Event Horizon: This is the boundary surrounding the black hole beyond which nothing, not even light, can escape. Once something crosses the event horizon, it's trapped within the black hole's grasp.
          
          Types of Black Holes: There are several types of black holes:
          
          Stellar Black Holes: Formed from the collapse of massive stars. They typically have a mass a few times that of the Sun.
          Supermassive Black Holes: Found at the centers of most galaxies, including our own Milky Way. They have masses millions or billions of times that of the Sun.
          Intermediate Black Holes: With masses between stellar and supermassive black holes. They're less understood and have been less frequently observed.
          Hawking Radiation: Proposed by physicist Stephen Hawking, this theory suggests that black holes can emit radiation due to quantum effects near the event horizon. Over vast periods of time, black holes could lose mass and eventually evaporate."
        />
        {/* Add other PlanetComponent instances as needed */}
      </div>
    </section>
  );
};

export default Planet;
